name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.2"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install colorlog fastapi matplotlib pandas pydantic seaborn uvicorn

    - name: Start FastAPI with timeout
      run: |
        source .venv/bin/activate
        timeout 10s uvicorn main:app --host 0.0.0.0 --port 8080
      
        
